firmNames <- c("General Life and Fire Assurance Company",
               "Ashton Vale Iron Company",
               "Bristol Waterworks Company",
               "London And Provincial Law Assurance Society",
               "Scinde Punjab and Delhi Railway Company",
               "Reliance Mutual Life Assurance Society",
               "Worcester City and Country Banking Company",
               "North British and Mercantile Insurance Company",
               "Alamillos Company",
               "Buena Ventura Company",
               "Fortuna Company",
               "Linares Lead Mining Company",
               "North Of Scotland Banking Company",
               "Rock Life Assurance Company",
               "Alabama Great Southern Railway Company",
               "Foreign and Colonial Government Trust Company",
               "Phosphate Company of Sombrero",
               "Birmingham Small Arms and Metal Company,",
               "Union Bank of Birmingham,",
               "Ceylon Company,",
               "Bromley Gas Consumer's Company",
               "Dublin and Meath Railway Company.",
               "Madras Railway Company",
               "Gas Light and Coke Company",
               "Standard Life Assurance Company",
               "South Eastern Railway Company",
               "Edinburgh Life Assurance Company",
               "",
               "Life Association of Scotland",
               "Scottish, Amicable Heritable Securities Association",
               "Northern Assurance Company",
               "United Mexican Mining Company",
               "Forth Bridge Railway Company",
               "National Bank of Scotland (deputy-governor)",
               "North British Railway Company",
               "Northern Assurance Company",
               "Hailstone Insurance Company",
               "General Revisionary and Investment Company",
               "Guarantee Society",
               "Union Rolling Stock Company",
               "London and St. Katharine Dock Company",
               "Thames and Mersey Marine Insurance Company",
               "Manchester and London Fire Insurance Company",
               "Manchester and London Fire Insurance Company",
               "London Small Property Property Trust,",
               "Commercial Bank of Alexandria",
               "Portpatrick Railway Company.",
               "Mysore Coffee Company",
               "Bristol Wagon Works Company",
               "Stuckey's Banking Company",
               "Berks and Hants Extension Railway Company",
               "Marlborough Railway Company",
               "National Provincial Bank of England",
               "Swindon Marlborough and Andover Railway Company",
               "Miller and General Fire Insurance Company",
               "Southport and West Lancashire Banking Company",
               "Agra Bank",
               "Caledonian Railway Company",
               "Callander and Oban Railway Company",
               "Edinburgh Gaslight Company",
               "Scottish Union and National Insurance Company",
               "Cagliari Gas and Water Company",
               "Victoria Dwellings Association",
               "Australian Mortgage, Land and Finance Company",
               "London Chartered Bank of Australia",
               "Marine Insurance Company",
               "Northern Heritable Securities Investment Company",
               "Ceylon Investment Association",
               "Langdale's Chemical Company",
               "Mutual Fire Insurance Corporation",
               "Rossendale Union Gas Company",
               "Silkstone and Dodworth Coal and Iron Company",
               "Fife Coal Company",
               "Leith Heritages Company",
               "North British Property Investment Company",
               "Scottish and New Zealand Investment Company",
               "Cork and Bandon Railway Company",
               "Dublin and Meath Railway Company",
               "McBireny and Company,",
               "Nabvan and Company",
               "Wakefield Gas Company",
               "Witeney Railway Company",
               "Montserrat Company",
               "Staffordshire Potteries Water works Company",
               "University Life Assurance Society",
               "Lynn and Fakenham Railway Company",
               "Yarmouth and North Norfolk (Light) Railway Company",
               "Metropolitan Association for Improving the Dwellings of the Industrial Classes",
               "Conishead Priory Hydropathic Company",
               "Belfast, Holywood and Banger Railway Company",
               "Alliance British and Foreign Life and Fire Assurance Company",
               "Alliance Marine Assurance Company",
               "Bank of Romania",
               "Imperial Ottoman Bank",
               "New London and Brazilian Bank",
               "East and West India Dock Company",
               "Imperial Fire Insurance Company",
               "Briton Life Association,",
               "South Indian Railway Company",
               "Bank of Australasia",
               "Newcastle-upon-Tyne and Gateshead Gas Company",
               "Newcastle Chemical Works Company",
               "Sea Insurance Company",
               "Van Mining Company",
               "Dundee and Newcastle Steam Shipping Company",
               "Dundee and Newcastle Railway Company",
               "Dundee Polar Fishing Company",
               "General Property Investment Association",
               "District Tramways Company",
               "Sheffield Wagon Company",
               "Indemnity Mutual Marine Assurance Company",
               "M.Olroyd and Sons",
               "Masonic Hall and Cheltenham Company",
               "Banbury and Cheltenham Direct Railway Company",
               "Devas, Routledge and Company",
               "Mining Company of Ireland",
               "Eagle Insurance Company",
               "General Reversionary and Investment Company",
               "Ultser Banking Company",
               "Wesleyan Methodist Trust Assurance Company.",
               "Barbados Railway Company.",
               "Newcastle Chemical Works Company,",
               "Sunderland Gas Company",
               "Preston Tramways Company",
               "National Arms and Ammunition Company",
               "Great Northern Railway Company",
               "Foster, Porter and Company",
               "City of Glasgow Life Assurance Company",
               "London and St. Katharine Dock Company",
               "ColOrado United Mining Cement Company",
               "Bradford Exchange Company",
               "St. George's Hall Company",
               "Halifax Commercial Banking Company",
               "South Essex Waterworks Company",
               "North British Australasian Company",
               "Ryde and Newport Railway Company",
               "New Waterworks Company",
               "Anglo American Telegraph Company",
               "Brazilian Submarine Telegraph Company",
               "Eastern and South Africa Telegraph Company",
               "Eastern Extension Australasia and China Telegraph Company",
               "Eastern Telegraph Company",
               "German Union Telegraph and Trust Company",
               "Newfoundland Land Company",
               "Submarine Cables Trust",
               "West India and Panama Telegraph Company",
               "Caledonian Banking Company",
               "Bank of British Columbia",
               "Bolivian Railway Company",
               "Home and Colonial Marine Insurance Company, ",
               "New Quebrada Company",
               "Scottish Provincial Assurance Company ",
               "Edinburgh Street Tramways Company",
               "Standard Property Investment Company",
               "Hornachos Silver Lead Mining Company",
               "Equitable Revisionary Interest Society",
               "Scottish Amicable Life Assurance Society",
               "Mungledye Tea Company",
               "Anglo Egyptian Banking Company",
               "Gereral Creadit and Discount Company,",
               "Scinde, Punjab and Delhi Railway Company.",
               "Belfast and Company Down Railway Company",
               "Commmercial Steam Ship Company",
               "Western and Brazilian Telegraph Company",
               "Falkland Island Company",
               "London and River Plate Bank,",
               "Commmercial Bank of Alexandria",
               "Merchant's Marine Insurrnce Company",
               "National Bank of India",
               "Eberhardt and Auroza Mining Company",
               "Halifax Joint Stock Banking Company",
               "Lancashire and Yorkshire Railway Company",
               "Nantyglo and Blaina Ironworks Company",
               "British and Australasian Trust and Loan Company",
               "National Safe Deosite Company",
               "Oriental Bank Corporation",
               "Union Bank of London",
               "London Assurance Corporation",
               "Bank of Australasia",
               "Commercial Union Assurance Company",
               "Londo Joint Stock Bank",
               "Tambrancherry Cofee Estate Company, ",
               "Masonic Hall and Club Copany, Ltd",
               "Gurntee Association of Scotland",
               "Kent Fire Insurance Company",
               "United Kent Life Assurance and Annuity Institution",
               "Argus Life Assurance Company",
               "Clerical Medical and General Life Assurrence Society",
               "Ntional Dwellings Society",
               "Hundderfield banking Company",
               "Longwood Gas Company",
               "Mutual Fire Insurance Corporation",
               "United Fire Re-Insurance Company",
               "Mutual Fire Insurance Corporation",
               "United Fire Re-Insurance Company",
               "Brown, Bayley and Dixon",
               "Fair Oak Colliery Company",
               "Farnley Iron Compony",
               "Cork, Blackrock and Passage Railway Company",
               "Dublin Artizans Dwellings Company,",
               "Dublin Wicklow and Wexford Railway Company",
               "Midland Great Western Railway of Ireland Company",
               "Royal Bank of Ireland ",
               "Standard Life Assurance Company",
               "Clifton Water Supply Company",
               "Halifax and Huddersfield Union Banking Company",
               "Law Union Fire and Life Insurance Company",
               "North Western Bank,",
               "West India and Pachifi Steamship Company",
               "Arnott and Company Dublin",
               "Bristol Steam Company ",
               "Cork Harbour Docks and Warehouses Company",
               "John Arnott and Co.. Of Belfast",
               "Sir John Arnott and Company, Glasgow, Cork",
               "Bristol Steam Navigation Company",
               "Glasgaw Caradon Consolidated Copper Mininig Company Ltd",
               "Hornachos Silver Lead Mining Company,",
               "Tharsis Sulphhur and Copper Company",
               "Bank of Africa",
               "West and Railway Terminus Hotel Company",
               "Bradford Exchange Company",
               "Bradford Vicoria Hotel Company",
               "St. George's Hall Company",
               "Scottish Provident Institution ",
               "Scottish and New Zealand Investment Company",
               "Breconm and Merthyr Tydfil junction Raiwy Company ",
               "City of London Real Property Company",
               "Emigrant and Colonist Aid Corporation",
               "Limmer Asphlte Paving Company",
               "Anglo French Fire Insurance Company",
               "Artisans Labourers nad Genral Dwellings Company Ltd",
               "London and Lancashire Life Assurance Company",
               "Railway Passenger's Assurance Company",
               "hand in Hand Insurance Society",
               "Imperial Fire Insurance Company",
               "Indemnity Mutual Insurance Company",
               "London and Westminster Bank",
               "Union Bank of Australia",
               "Albert New Mill Company",
               "National Boiler Insurance Company",
               "Buenos Ayres Great Southern Railway Company",
               "Lancashire Bank of th e River Plate",
               "District Banking Company",
               "Leeds Tramways Company",
               "Brown, Bayley and Dixon",
               "House Property and Investment Company",
               "London and Lancashire Insurance Corporation",
               "East Lincolnchire Railway Company ",
               "Imperial Fire Insurance Company",
               "Idemnity Mutual Marine Assurance Company",
               "San paulo (Brazilian) Rialway Company",
               "Trust and Loan Company of Canada.",
               "North Stafforshire Railway Company",
               "Northern Counties Bank",
               "Isle of Wight Railway Company",
               "Highland Railway Company",
               "Lowwood Gunpowder Company",
               "Mersey Steel  and Iron Company",
               "National Bank of India",
               "West African Company",
               "Limerick Railway Company",
               "National Bank of India",
               "City Bank ",
               "Ultser Banking Company",
               "Star Life Assurance Society",
               "Gateshead gas Company",
               "Brazilian Street Railway Company",
               "Manchester, Sheffiels and Lincolncshire Railway Company",
               "Trent Ancholme and Grimsly Railway Company ",
               "London  Necroplis and National Mansoleum Company",
               "Metropolitan and St. John's Wood Railway Company ",
               "Rhymney Railway Company",
               "Russinan (Vyksounsky) Ironworks Company ",
               "Sanbre and Meuse Railway Company ",
               "Birmingham Joint Stock Bank",
               "Stratford-upon-Avon Railway Company ",
               "Cannock and Huntington Colliery Company",
               "Royal Excahnge Bank",
               "Stafforshire Fire Insurance Company",
               "Kirkcaldy Gaslight Company",
               "Sanbre and Meuse Railway Company ",
               "London and San Francies Bank",
               "Darlington Iron Company ",
               "Hutton Henry Coal Company ",
               "Continental Union Gas Company",
               "European Gas Company",
               "Oriental Gas Company",
               "Union dez Gaz",
               "Legal And Genral Life Assurance Society",
               "Commerical Gas Company",
               "London Taverns Company,",
               "Legal And Genral Life Assurance Society",
               "London Life Assurance",
               "Union Steam Ship Company",
               "Shropshire and North Sons",
               "University Life Assurance Society",
               "Penarth hazbour, Dock and Railway Company",
               "Genreal Hailstrom Innsurrance Society",
               "Norwich Union Fire Innsurrence Company",
               "Norwich Waterworks Company",
               "Law Life Assurnce Society",
               "Hull Dock Company",
               "Capital and Countics Bank",
               "Cleator and Working Junction Railway Company",
               "Land Mortagage Bank of India",
               "Lower Assam Company",
               "San Paulo Gas Company Ltd",
               "North British and Mercantile Insurance Company.",
               "Sclergy Assurance Society",
               "Britannia Mills Flour and Bread Company, Birmingham",
               "Friends Provident Instution",
               "Montserrat Company",
               "Staffordshire Joint Stock Bank",
               "East Argentine Railway Company",
               "birmingham Railway Carrige and Waggoon Company,",
               "Derby and Derbtshire Bank",
               "Brown Davis and Company",
               "Great Westrn Railway Company of Canada",
               "Midland Counties Val de Travers paving Company",
               "Altlantica and Railways Company,",
               "Barnet District Gas And Water Cpomany",
               "Croydon Tramways Company",
               "Bank of South Australia",
               "Emigrant and Colonist Aid Corporation",
               "Bristol Ccity Hotel Company",
               "Grant Juction Waterworkers Company",
               "British Linen Company Bank",
               "East London Waterworkes",
               "Witeney Railway Company",
               "Buxton Place Company",
               "London and North Wesetern Railway Company",
               "Manchester Junction and Company Railway",
               "North London Rilway Company",
               "Old, Ashton-under-Lyne G.B.J Rialway Company",
               "Leicestershire Banking Company",
               "University Life Assurance Society",
               "Leominister and Kington Railway Company.",
               "Seaton and Beer Railway Company",
               "Caba Sammarine Telegraph Company, ",
               "Direct Spanish Telegraph Company",
               "India Ruber, Gutta-percha and Telegraph Works Company,",
               "Sidmounth Railway Company",
               "West Coast of America Telegarph Company",
               "Alexander Theatre Company",
               "Hayton and Roby Gas Company ",
               "National Steamsship Company ",
               "Lancashire Insurance Company",
               "Consolidated Bank",
               "Edinburgh and Direct Gas Company",
               "Hall Street Tramways",
               "Manor Park Cemetery Company",
               "Anglo-Pacific Trust and Loan Company",
               "Yorkshire Fire and Life Insurance Company.",
               "Friends Provident Instution",
               "Sbeffeld Bankin Company",
               "Crompton and Evens Union Bank,",
               "Anglo American Telegraph Company, Limeted.",
               "Great Eastern Steamship Company",
               "Lloyd's Cambrain Company Limtited",
               "Value Foundery Company",
               "Belfats Standard Fire Office Company",
               "Manchester and Liverpool District Banking Company",
               "United Discount Corporation",
               "Cazon Exhibition Hall Company",
               "Imperial Fire Insurance Compony",
               "Acident Insurrnce Association of Scoatland",
               "Bank of Scotland",
               "Edinburgh Life Assurance Company",
               "National Guarntee and Suretyship Association",
               "Colorado Mortgage and Investment Company of London Ltd.",
               "Forth and North Western Railway Company",
               "North of Scotland Canadian Mortgage Company",
               "City of Glasgow Union Railway Company",
               "City of Life Assurance Company",
               "Glasgow and South Wetsrn Railway Company",
               "Commercial Union Assurance Company",
               "Royal Water Works Company",
               "Roayl Exchange Assurance Corporation",
               "Bessbrook Spinig Company ",
               "Dund and Newry Steam packet Company",
               "Joseph Rodgers and Sons",
               "Sunnery Colliery Company",
               "Samuel Fox and Company",
               "Sbeffeld Bankin Company",
               "Stocksbridge Railway Company",
               "Devon and Somerset Railway Company",
               "Mcconnell and Company",
               "Bank of Enagland",
               "North British and Mercantile Insurance Company.",
               "Baring Brother and Co.,",
               "Union Marine Insurance Company",
               "Chillington Iron Company",
               "Midland Steam Boiler Inspection and Asurence Company",
               "Tunisian Railways Company",
               "East Glaoucester-Shire Railway Company",
               "West Middlesex Waterworks Company",
               "Mnutz'z Metal Company",
               "Chillington Iron Company",
               "General Reversionary and Investment Company",
               "Palace and Burlington Hotels Company",
               "Bdanube and Black Sea Railway and k.Harbour Company",
               "Eats Cornaeall  Mineral Company",
               "East Glouccestershire Rialway Company",
               "Madras Railway Company",
               "New South Walse Mortagage, Laon and Agency Company Limietd",
               "Standard Bank of British South Africa",
               "Great Westrn Railway Company of Canada",
               "Colombo Gas and Water Company",
               "Forest of Dean Cenatral Railway Company ",
               "Royal Mail Steam Packet Company",
               "South Walse Mineral Railway Company",
               "Westmainster and General Life Assurance Association",
               "Weymouth and Portland Railway Company",
               "Barlow & Sons",
               "Miller and General Fire Insurance Company",
               "English and Scottish law Assurance Association",
               "Barlow & Jones",
               "Mutual Fire Insurance Corporation",
               "Union Bank of Manchester",
               "Wesleyan Methodist Trust Assurance Company.",
               "Indo European Telegraph Compny",
               "East London Waterworkes",
               "Wrexham Mold and Connah's Quay Railway Company",
               "Tendring Hndred Railway Company",
               "bank of Bolton",
               "Provincial Insurance Company",
               "Royall Srdinian Railway Company",
               "Wrexham Mold and Connah's Quay Railway Company",
               "West of England Fire and Life Insurance Company",
               "Alliance Marine Assurance Company.",
               "London Chartered Bank of Australia",
               "African Steam Ship Company",
               "Floating Life Assurance Society",
               "Provinvcial Bank of Ireland",
               "Blane Valley Railway Station",
               "William Corbit and Company",
               "Fylde Waterworks Company",
               "Gas Purification and Chemical Company",
               "Johnson's Saccharum Company",
               "Mediterranean Hotel Company",
               "West London Commercial Bank",
               "United Kingdom Tempernce and General Provident Institution",
               "Cork, Blackrock and Passage Railway Company",
               "Cork Steam Packet Company",
               "Metropolitian Life Insurance Society",
               "National Provident Institution",
               "Manchester and Milford Railway Company",
               "Seaton and Beer Railway Company",
               "Staveley Coal and Iron Company",
               "Brington Hotel Company",
               "London Financial Assocition",
               "national Fire Insurance Corporation",
               "Northamtonshire Banking Company",
               "Mining Company of Ireland Ltd.",
               "North Albion Proerty Investment Company",
               "Royal Insurance Company ",
               "Broseley Gas Coke Company",
               "Bristol Ccity Hotel Company",
               "Western Wagon Company Limietd",
               "Bucks and Oxan Union Bank",
               "Union Bank of London",
               "John Harrison and Co",
               "Bath Gas Light and Coke Company",
               "Mercantile Bank of Peru",
               "British Equitable Assurance Company",
               "Westmainster and General Life Assurance Association",
               "Waterlow and Sons",
               "Imperial Continental Gas Association",
               "Earle's Shipbulding and Company",
               "Sheffiels Union Banking Company",
               "Cornawalll Railway Company",
               "Great Northern Railway Company",
               "Newent Railway Company",
               "Ross and Ledbury Railway Company",
               "Mid hants Railway Company",
               "Sttford and Uttoxeter Railway",
               "Bradford Commercial Joint Stock Bank",
               "Colone Valley Water Company.",
               "Atlantic light Company",
               "Sons & Co.Brokers",
               "International Marine Insurance of Liverpool",
               "London and North Wesetern Railway Company",
               "Henry Bath & Son Swansea",
               "Galmorganshire Nbanking Company",
               "Libiola Minig Company",
               "Swansea Bank",
               "Alhambra Company",
               "Broseley Gas Coke Company",
               "Sovergen Life Assurance Company",
               "San Paulo Gas Company Ltd",
               "Mutual Tontine Association",
               "Star Life Assurance Society",
               "Llangollen and Corwen Railway Company",
               "Playmonth and Dartmoor Railway Company.",
               "Sanbre and Meuse Railway Company ",
               "Buckfastleigh, Totnes and South Devon Railway Company",
               "Central Wales and Carmarthen Junction Railway Company",
               "Devon and Cornawall Railway Company",
               "English and Foreign Credit Copmany",
               "Kilkenny Junction Railway Company",
               "London Financial Assocition",
               "Mid hants Railway Company",
               "Muswell-Hills Estete Company (Alton Lines)",
               "Plymouth and Dartmoor Railway Company",
               "Potteries, Shrewsbury and North Walse Railway Company",
               "Salisbury and Dorest Junction Rilway Company",
               "Birdseye Creek Gold Mining Company,",
               "Midland Couties Insurance Comnpany",
               "Regent's Canal Company",
               "Antioquia Company",
               "Eberhardt and Auroza Mining Company",
               "Frontino and Bolivia Mines and Smeltin Company",
               "West Pateley Bridge Lead mines",
               "Royal Excahnge Company, Leeds,",
               "Scottish Widows Fund Mutual Life Assurance Society",
               "Peninsula and Oriental Steam Navigation Company",
               "Bayley and Dixon",
               "New Westmister Brewery Company",
               "Harrow District Gas Company.",
               "Atlas Assurance Company",
               "Londo Joint Stock Bank",
               "North London Rilway Company",
               "Provinvcial Bank of Ireland",
               "East Glouccestershire Rialway Company",
               "London and North Wesetern Railway Company",
               "Assam Company",
               "Conde d'Eu Railway Company",
               "East Argentine Railway Company",
               "Qude and Rohilkund Railway Company",
               "Colorado United Mining Company",
               "University Life Assurance Society",
               "Clerical Medical and General Life Assurrence Society",
               "Birmingham and Midland Bank",
               "Danube and Black Sea Railway and Kustendjie Horbour Ltd",
               "Cazon Exhibition Hall Company",
               "Solihull Gas Company",
               "Lincon aand Lindesy Bankig Company",
               "Scottish Wagon Company",
               "The South Eastrn Railway Company",
               "Delhi and london Bank",
               "Halesowen Railway Company",
               "Longton Adderley Railway Compny",
               "Swansea and Mumbles Railway Company",
               "Southwark and Deptford Tramways Company",
               "Darlington Iron Company ",
               "Foreign and Colonial Tunnelling and Prospecting Company",
               "East Indian Railway Company",
               "law Fire Insurance Society",
               "Forth Bridge Railway Company",
               "Fire Office and the Providennt Life Office",
               "Fire Office and the Providennt Life Office",
               "West India and Pachifi Steamship Company",
               "British Shipowners Company",
               "Peason and Knowles Coal and Iron Company",
               "New Sharlston Colliers Company",
               "Friends Provident Instution",
               "Ottoman Gas Company",
               "Commercial Union Bank",
               "New Londo and Brazilian Bank",
               "London Cemetery Company",
               "Mercantile Bank of the  River Plate",
               "Globe marine Insurance Company",
               "National Guarntee and Suretyship Association",
               "Scottish, Amicable Heritable Securities Association.",
               "Life Association of Scotland",
               "Roayal Insurance Company",
               "Thames and Mersey Marine Insurance Company",
               "Uttoxeter and Ashbourn Union Bank",
               "Hendon Paper Works Company",
               "Langdale's Chemical Company,",
               "North Railway Company",
               "Scottish Provident Investment Company",
               "Reversionary Interest Society",
               "Broxburn Oli Company",
               "Recife and San Francisco Pernambuco Railway Company",
               "Munster Bank",
               "London and Westminster Bank",
               "London Cemetery Company",
               "Fal-mouth Docks  Company",
               "Masonic and Genaral Life Assurance Company",
               "Accident Insurance Company",
               "Horseley Company",
               "Provincail law Assurance Society",
               "City of Postdam Waterworks Company",
               "Governmetn's Stock Investment Company",
               "London Steamboat Company",
               "North Westrn Fire Insurance Company",
               "Grand Hotle Company, Scarbrough,",
               "Eberle'd hotels and Resturant Company",
               "English and Australian Copper Copmpany",
               "Berks and Hants Extension Railway Company",
               "Bank of Enagland",
               "Eastrn Bengal Railway Company",
               "Guardian Fire and Life Assurance Company,",
               "London Genral Omnibus Compny",
               "Sun Fire Office ",
               "Star Life Assurance Society",
               "Natal Land and Colonization Company",
               "Natal Platations Company",
               "Colonial Company",
               "National Bank of India",
               "Valde Travers Paving Company",
               "City of London Brewery Company",
               "panulcillo Copper Company",
               "Lambeth Waterworks Company",
               "Corwen and Bala Railway Company",
               "Vale of Langllen Railway Company",
               "Central Pacific Coal and Coke Company",
               "Trust and Agency Company Of Australaisa and China Telegraph Company",
               "Imperial Fire Insurance Company",
               "Railway Passenger's Assurance Company",
               "Cape Copper Minig Company",
               "Chilinburch Iron Company",
               "English Bank Rio de Janerio",
               "Law Reversionary Interset Society",
               "Newport Abercarn Black Vein Stem Coal Company",
               "Newport Tramways Company",
               "Western and Brazilian Telegraph Company",
               "Union Marine Insurance Company",
               "Cantile Stemship Company",
               "Birmingham Canal Navigations ",
               "Dunddalk, Newry and Greenore Raiilway Compony",
               "Shorpshire Union Railways and Canal Company",
               "Vale of Towy RailwayCompany.",
               "Llanelly Railway and Dock Company",
               "Canada Company",
               "Economic Life Assurance Society",
               "Highland Railway Company",
               "General Mining Association",
               "Linares Lead Mining Company,",
               "Univercitty Life Assurance Society",
               "Oxfords and Cmabridge Club Pall Mall S.W",
               "Imperial live Stock Insurance Association",
               "Norwich and London Accident Inssurence Association",
               "Edinburgh Hertbnle Security Company",
               "Great Northern and Western of Irelan Railway Company",
               "J.Bingham & Co. ",
               "Liverpool Union Bank",
               "National Steamsship Company ",
               "Queen Insurance Company",
               "Earles Shipbuling and Engineering Company,",
               "Laurie and Marner",
               "British and Forgien Marine Insurance Company,",
               "Liverpool north Shore Flour and Rice Mill Company",
               "Equitable Mortgage Bank of india",
               "Lincoln Waggon and Engine Company",
               "Goyenche & Co.",
               "Bridgewater Navigation Company",
               "Wells Birch & Co.,",
               "W. Singleton Birch & Sons Limietd",
               "Star Life Assurance Society",
               "San Paulo Railway Company",
               "East Norfolk Railway Company",
               "Nottingham And Nottinghamshire Bankig Company",
               "T.I Birkin & Co. Manufacutre ",
               "Cantile Stemship Company",
               "Martime Innsurance Company",
               "Manchster and Country bank",
               "Preston Banking Company.",
               "Manchester and Salford Bank",
               "Provindent Clerks and General Accident Insurance Company Liimited ",
               "Provindent Clerks and General Garuntee Association Liimited ",
               "Provident Clerk's Mutual Life Assurnce Association ",
               "Lancashire and Yorkshire Waggon Company",
               "Eagle Insurance Company",
               "London Tibury and Southend Railway Company",
               "Dunaburg and Witepsk Railway Company",
               "Swedish Association",
               "Swedish Central Railway Company",
               "Thames barge Company",
               "Netherlands Land Enclosure Company",
               "Irnus of Court Hotel",
               "Pelsall Coal and iron Company",
               "Sandwell Park Colliery Company",
               "Worccster City and Country Banking Company",
               "Dandu Tug and Lighter Company",
               "Langdale's Chemical Manure Company",
               "Newcastle Chemical Works Company,",
               "St. Bede Chemical Company",
               "Clerical Medical and General Life Assurrence Society",
               "Surrey Consumers Gas Company Tottnham and Edmonton Gas and Coke Company",
               "National Bank of Scotland (deputy-governor)",
               "English and Scottish Investment Company of Canada",
               "Macdonals & Co., Cape ",
               "Lancashire Insurance Company",
               "National Bank of Scotland Scottish Equitable Life Assurance Society",
               "Surrey Commercial Dock Company",
               "Legal And Genral Life Assurance Society",
               "Great Indian Peninsula Railway Company",
               "Madras Railway Company",
               "Masonic Hall and Club Copany, Ltd",
               "Halesowen Railway Company",
               "Port Phillip and Colonial Gold Minig Company",
               "Victoria (london) Mining Company",
               "Bilbao Iron Ore Company",
               "Peason and Knowles Coal and Iron Company",
               "Warrington Waggon Company",
               "Calais Tramwys Company",
               "British and Forgien Marine Insurance Company,",
               "London and Lancashire Life Assurance Company")

for (i in 1:length(firmNames)) { similarityList[[i]]$name[1] <- firmNames[i] }